//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWindApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustomerTitle {
            get {
                return this.CustomerTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTitleField, value) != true)) {
                    this.CustomerTitleField = value;
                    this.RaisePropertyChanged("CustomerTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIDField;
        
        private System.Nullable<int> EmployeeIDField;
        
        private System.Nullable<System.DateTime> OrderDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Products", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Products : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private decimal UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employees", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name FirstCustomerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FirstCustomer", ReplyAction="*")]
        NorthWindApplication.ServiceReference1.FirstCustomerResponse FirstCustomer(NorthWindApplication.ServiceReference1.FirstCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FirstCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.FirstCustomerResponse> FirstCustomerAsync(NorthWindApplication.ServiceReference1.FirstCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name LastCustomerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LastCustomer", ReplyAction="*")]
        NorthWindApplication.ServiceReference1.LastCustomerResponse LastCustomer(NorthWindApplication.ServiceReference1.LastCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LastCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.LastCustomerResponse> LastCustomerAsync(NorthWindApplication.ServiceReference1.LastCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NextCustomer", ReplyAction="*")]
        NorthWindApplication.ServiceReference1.NextCustomerResponse NextCustomer(NorthWindApplication.ServiceReference1.NextCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NextCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.NextCustomerResponse> NextCustomerAsync(NorthWindApplication.ServiceReference1.NextCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrevCustomer", ReplyAction="*")]
        NorthWindApplication.ServiceReference1.PrevCustomerResponse PrevCustomer(NorthWindApplication.ServiceReference1.PrevCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrevCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.PrevCustomerResponse> PrevCustomerAsync(NorthWindApplication.ServiceReference1.PrevCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        NorthWindApplication.ServiceReference1.AddResponse Add(NorthWindApplication.ServiceReference1.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.AddResponse> AddAsync(NorthWindApplication.ServiceReference1.AddRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        NorthWindApplication.ServiceReference1.EditResponse Edit(NorthWindApplication.ServiceReference1.EditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.EditResponse> EditAsync(NorthWindApplication.ServiceReference1.EditRequest request);
        
        // CODEGEN: Generating message contract since element name ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        NorthWindApplication.ServiceReference1.DeleteResponse Delete(NorthWindApplication.ServiceReference1.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.DeleteResponse> DeleteAsync(NorthWindApplication.ServiceReference1.DeleteRequest request);
        
        // CODEGEN: Generating message contract since element name Cust from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrdersData", ReplyAction="*")]
        NorthWindApplication.ServiceReference1.OrdersDataResponse OrdersData(NorthWindApplication.ServiceReference1.OrdersDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrdersData", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.OrdersDataResponse> OrdersDataAsync(NorthWindApplication.ServiceReference1.OrdersDataRequest request);
        
        // CODEGEN: Generating message contract since element name CustomerID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceOrder", ReplyAction="*")]
        NorthWindApplication.ServiceReference1.PlaceOrderResponse PlaceOrder(NorthWindApplication.ServiceReference1.PlaceOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlaceOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.PlaceOrderResponse> PlaceOrderAsync(NorthWindApplication.ServiceReference1.PlaceOrderRequest request);
        
        // CODEGEN: Generating message contract since element name AddProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProducts", ReplyAction="*")]
        NorthWindApplication.ServiceReference1.AddProductsResponse AddProducts(NorthWindApplication.ServiceReference1.AddProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.AddProductsResponse> AddProductsAsync(NorthWindApplication.ServiceReference1.AddProductsRequest request);
        
        // CODEGEN: Generating message contract since element name AddEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployees", ReplyAction="*")]
        NorthWindApplication.ServiceReference1.AddEmployeesResponse AddEmployees(NorthWindApplication.ServiceReference1.AddEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.AddEmployeesResponse> AddEmployeesAsync(NorthWindApplication.ServiceReference1.AddEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FirstCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FirstCustomer", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.FirstCustomerRequestBody Body;
        
        public FirstCustomerRequest() {
        }
        
        public FirstCustomerRequest(NorthWindApplication.ServiceReference1.FirstCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FirstCustomerRequestBody {
        
        public FirstCustomerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FirstCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FirstCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.FirstCustomerResponseBody Body;
        
        public FirstCustomerResponse() {
        }
        
        public FirstCustomerResponse(NorthWindApplication.ServiceReference1.FirstCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FirstCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWindApplication.ServiceReference1.Customer FirstCustomerResult;
        
        public FirstCustomerResponseBody() {
        }
        
        public FirstCustomerResponseBody(NorthWindApplication.ServiceReference1.Customer FirstCustomerResult) {
            this.FirstCustomerResult = FirstCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LastCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LastCustomer", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.LastCustomerRequestBody Body;
        
        public LastCustomerRequest() {
        }
        
        public LastCustomerRequest(NorthWindApplication.ServiceReference1.LastCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LastCustomerRequestBody {
        
        public LastCustomerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LastCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LastCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.LastCustomerResponseBody Body;
        
        public LastCustomerResponse() {
        }
        
        public LastCustomerResponse(NorthWindApplication.ServiceReference1.LastCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LastCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWindApplication.ServiceReference1.Customer LastCustomerResult;
        
        public LastCustomerResponseBody() {
        }
        
        public LastCustomerResponseBody(NorthWindApplication.ServiceReference1.Customer LastCustomerResult) {
            this.LastCustomerResult = LastCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextCustomer", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.NextCustomerRequestBody Body;
        
        public NextCustomerRequest() {
        }
        
        public NextCustomerRequest(NorthWindApplication.ServiceReference1.NextCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NextCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        public NextCustomerRequestBody() {
        }
        
        public NextCustomerRequestBody(string ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.NextCustomerResponseBody Body;
        
        public NextCustomerResponse() {
        }
        
        public NextCustomerResponse(NorthWindApplication.ServiceReference1.NextCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NextCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWindApplication.ServiceReference1.Customer NextCustomerResult;
        
        public NextCustomerResponseBody() {
        }
        
        public NextCustomerResponseBody(NorthWindApplication.ServiceReference1.Customer NextCustomerResult) {
            this.NextCustomerResult = NextCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrevCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrevCustomer", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.PrevCustomerRequestBody Body;
        
        public PrevCustomerRequest() {
        }
        
        public PrevCustomerRequest(NorthWindApplication.ServiceReference1.PrevCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrevCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        public PrevCustomerRequestBody() {
        }
        
        public PrevCustomerRequestBody(string ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrevCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrevCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.PrevCustomerResponseBody Body;
        
        public PrevCustomerResponse() {
        }
        
        public PrevCustomerResponse(NorthWindApplication.ServiceReference1.PrevCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrevCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWindApplication.ServiceReference1.Customer PrevCustomerResult;
        
        public PrevCustomerResponseBody() {
        }
        
        public PrevCustomerResponseBody(NorthWindApplication.ServiceReference1.Customer PrevCustomerResult) {
            this.PrevCustomerResult = PrevCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(NorthWindApplication.ServiceReference1.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(string ID, string CompName, string CustName, string CustTitle, string Address) {
            this.ID = ID;
            this.CompName = CompName;
            this.CustName = CustName;
            this.CustTitle = CustTitle;
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(NorthWindApplication.ServiceReference1.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(bool AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.EditRequestBody Body;
        
        public EditRequest() {
        }
        
        public EditRequest(NorthWindApplication.ServiceReference1.EditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address;
        
        public EditRequestBody() {
        }
        
        public EditRequestBody(string ID, string CompName, string CustName, string CustTitle, string Address) {
            this.ID = ID;
            this.CompName = CompName;
            this.CustName = CustName;
            this.CustTitle = CustTitle;
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.EditResponseBody Body;
        
        public EditResponse() {
        }
        
        public EditResponse(NorthWindApplication.ServiceReference1.EditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditResult;
        
        public EditResponseBody() {
        }
        
        public EditResponseBody(bool EditResult) {
            this.EditResult = EditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(NorthWindApplication.ServiceReference1.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(NorthWindApplication.ServiceReference1.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteResult;
        
        public DeleteResponseBody() {
        }
        
        public DeleteResponseBody(bool DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdersDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdersData", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.OrdersDataRequestBody Body;
        
        public OrdersDataRequest() {
        }
        
        public OrdersDataRequest(NorthWindApplication.ServiceReference1.OrdersDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrdersDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWindApplication.ServiceReference1.Customer Cust;
        
        public OrdersDataRequestBody() {
        }
        
        public OrdersDataRequestBody(NorthWindApplication.ServiceReference1.Customer Cust) {
            this.Cust = Cust;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdersDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrdersDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.OrdersDataResponseBody Body;
        
        public OrdersDataResponse() {
        }
        
        public OrdersDataResponse(NorthWindApplication.ServiceReference1.OrdersDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrdersDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWindApplication.ServiceReference1.OrderDetails[] OrdersDataResult;
        
        public OrdersDataResponseBody() {
        }
        
        public OrdersDataResponseBody(NorthWindApplication.ServiceReference1.OrderDetails[] OrdersDataResult) {
            this.OrdersDataResult = OrdersDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceOrder", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.PlaceOrderRequestBody Body;
        
        public PlaceOrderRequest() {
        }
        
        public PlaceOrderRequest(NorthWindApplication.ServiceReference1.PlaceOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int EmployeeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ProductID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal UnitPrice;
        
        public PlaceOrderRequestBody() {
        }
        
        public PlaceOrderRequestBody(string CustomerID, int EmployeeID, int ProductID, int Quantity, decimal UnitPrice) {
            this.CustomerID = CustomerID;
            this.EmployeeID = EmployeeID;
            this.ProductID = ProductID;
            this.Quantity = Quantity;
            this.UnitPrice = UnitPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PlaceOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PlaceOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.PlaceOrderResponseBody Body;
        
        public PlaceOrderResponse() {
        }
        
        public PlaceOrderResponse(NorthWindApplication.ServiceReference1.PlaceOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PlaceOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PlaceOrderResult;
        
        public PlaceOrderResponseBody() {
        }
        
        public PlaceOrderResponseBody(bool PlaceOrderResult) {
            this.PlaceOrderResult = PlaceOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProducts", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.AddProductsRequestBody Body;
        
        public AddProductsRequest() {
        }
        
        public AddProductsRequest(NorthWindApplication.ServiceReference1.AddProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProdID;
        
        public AddProductsRequestBody() {
        }
        
        public AddProductsRequestBody(int ProdID) {
            this.ProdID = ProdID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.AddProductsResponseBody Body;
        
        public AddProductsResponse() {
        }
        
        public AddProductsResponse(NorthWindApplication.ServiceReference1.AddProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWindApplication.ServiceReference1.Products[] AddProductsResult;
        
        public AddProductsResponseBody() {
        }
        
        public AddProductsResponseBody(NorthWindApplication.ServiceReference1.Products[] AddProductsResult) {
            this.AddProductsResult = AddProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployees", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.AddEmployeesRequestBody Body;
        
        public AddEmployeesRequest() {
        }
        
        public AddEmployeesRequest(NorthWindApplication.ServiceReference1.AddEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmployeesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int EmpID;
        
        public AddEmployeesRequestBody() {
        }
        
        public AddEmployeesRequestBody(int EmpID) {
            this.EmpID = EmpID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public NorthWindApplication.ServiceReference1.AddEmployeesResponseBody Body;
        
        public AddEmployeesResponse() {
        }
        
        public AddEmployeesResponse(NorthWindApplication.ServiceReference1.AddEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NorthWindApplication.ServiceReference1.Employees[] AddEmployeesResult;
        
        public AddEmployeesResponseBody() {
        }
        
        public AddEmployeesResponseBody(NorthWindApplication.ServiceReference1.Employees[] AddEmployeesResult) {
            this.AddEmployeesResult = AddEmployeesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : NorthWindApplication.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<NorthWindApplication.ServiceReference1.WebService1Soap>, NorthWindApplication.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWindApplication.ServiceReference1.FirstCustomerResponse NorthWindApplication.ServiceReference1.WebService1Soap.FirstCustomer(NorthWindApplication.ServiceReference1.FirstCustomerRequest request) {
            return base.Channel.FirstCustomer(request);
        }
        
        public NorthWindApplication.ServiceReference1.Customer FirstCustomer() {
            NorthWindApplication.ServiceReference1.FirstCustomerRequest inValue = new NorthWindApplication.ServiceReference1.FirstCustomerRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.FirstCustomerRequestBody();
            NorthWindApplication.ServiceReference1.FirstCustomerResponse retVal = ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).FirstCustomer(inValue);
            return retVal.Body.FirstCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.FirstCustomerResponse> NorthWindApplication.ServiceReference1.WebService1Soap.FirstCustomerAsync(NorthWindApplication.ServiceReference1.FirstCustomerRequest request) {
            return base.Channel.FirstCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.FirstCustomerResponse> FirstCustomerAsync() {
            NorthWindApplication.ServiceReference1.FirstCustomerRequest inValue = new NorthWindApplication.ServiceReference1.FirstCustomerRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.FirstCustomerRequestBody();
            return ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).FirstCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWindApplication.ServiceReference1.LastCustomerResponse NorthWindApplication.ServiceReference1.WebService1Soap.LastCustomer(NorthWindApplication.ServiceReference1.LastCustomerRequest request) {
            return base.Channel.LastCustomer(request);
        }
        
        public NorthWindApplication.ServiceReference1.Customer LastCustomer() {
            NorthWindApplication.ServiceReference1.LastCustomerRequest inValue = new NorthWindApplication.ServiceReference1.LastCustomerRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.LastCustomerRequestBody();
            NorthWindApplication.ServiceReference1.LastCustomerResponse retVal = ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).LastCustomer(inValue);
            return retVal.Body.LastCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.LastCustomerResponse> NorthWindApplication.ServiceReference1.WebService1Soap.LastCustomerAsync(NorthWindApplication.ServiceReference1.LastCustomerRequest request) {
            return base.Channel.LastCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.LastCustomerResponse> LastCustomerAsync() {
            NorthWindApplication.ServiceReference1.LastCustomerRequest inValue = new NorthWindApplication.ServiceReference1.LastCustomerRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.LastCustomerRequestBody();
            return ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).LastCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWindApplication.ServiceReference1.NextCustomerResponse NorthWindApplication.ServiceReference1.WebService1Soap.NextCustomer(NorthWindApplication.ServiceReference1.NextCustomerRequest request) {
            return base.Channel.NextCustomer(request);
        }
        
        public NorthWindApplication.ServiceReference1.Customer NextCustomer(string ID) {
            NorthWindApplication.ServiceReference1.NextCustomerRequest inValue = new NorthWindApplication.ServiceReference1.NextCustomerRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.NextCustomerRequestBody();
            inValue.Body.ID = ID;
            NorthWindApplication.ServiceReference1.NextCustomerResponse retVal = ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).NextCustomer(inValue);
            return retVal.Body.NextCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.NextCustomerResponse> NorthWindApplication.ServiceReference1.WebService1Soap.NextCustomerAsync(NorthWindApplication.ServiceReference1.NextCustomerRequest request) {
            return base.Channel.NextCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.NextCustomerResponse> NextCustomerAsync(string ID) {
            NorthWindApplication.ServiceReference1.NextCustomerRequest inValue = new NorthWindApplication.ServiceReference1.NextCustomerRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.NextCustomerRequestBody();
            inValue.Body.ID = ID;
            return ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).NextCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWindApplication.ServiceReference1.PrevCustomerResponse NorthWindApplication.ServiceReference1.WebService1Soap.PrevCustomer(NorthWindApplication.ServiceReference1.PrevCustomerRequest request) {
            return base.Channel.PrevCustomer(request);
        }
        
        public NorthWindApplication.ServiceReference1.Customer PrevCustomer(string ID) {
            NorthWindApplication.ServiceReference1.PrevCustomerRequest inValue = new NorthWindApplication.ServiceReference1.PrevCustomerRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.PrevCustomerRequestBody();
            inValue.Body.ID = ID;
            NorthWindApplication.ServiceReference1.PrevCustomerResponse retVal = ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).PrevCustomer(inValue);
            return retVal.Body.PrevCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.PrevCustomerResponse> NorthWindApplication.ServiceReference1.WebService1Soap.PrevCustomerAsync(NorthWindApplication.ServiceReference1.PrevCustomerRequest request) {
            return base.Channel.PrevCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.PrevCustomerResponse> PrevCustomerAsync(string ID) {
            NorthWindApplication.ServiceReference1.PrevCustomerRequest inValue = new NorthWindApplication.ServiceReference1.PrevCustomerRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.PrevCustomerRequestBody();
            inValue.Body.ID = ID;
            return ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).PrevCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWindApplication.ServiceReference1.AddResponse NorthWindApplication.ServiceReference1.WebService1Soap.Add(NorthWindApplication.ServiceReference1.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public bool Add(string ID, string CompName, string CustName, string CustTitle, string Address) {
            NorthWindApplication.ServiceReference1.AddRequest inValue = new NorthWindApplication.ServiceReference1.AddRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.AddRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.CompName = CompName;
            inValue.Body.CustName = CustName;
            inValue.Body.CustTitle = CustTitle;
            inValue.Body.Address = Address;
            NorthWindApplication.ServiceReference1.AddResponse retVal = ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.AddResponse> NorthWindApplication.ServiceReference1.WebService1Soap.AddAsync(NorthWindApplication.ServiceReference1.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.AddResponse> AddAsync(string ID, string CompName, string CustName, string CustTitle, string Address) {
            NorthWindApplication.ServiceReference1.AddRequest inValue = new NorthWindApplication.ServiceReference1.AddRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.AddRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.CompName = CompName;
            inValue.Body.CustName = CustName;
            inValue.Body.CustTitle = CustTitle;
            inValue.Body.Address = Address;
            return ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWindApplication.ServiceReference1.EditResponse NorthWindApplication.ServiceReference1.WebService1Soap.Edit(NorthWindApplication.ServiceReference1.EditRequest request) {
            return base.Channel.Edit(request);
        }
        
        public bool Edit(string ID, string CompName, string CustName, string CustTitle, string Address) {
            NorthWindApplication.ServiceReference1.EditRequest inValue = new NorthWindApplication.ServiceReference1.EditRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.EditRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.CompName = CompName;
            inValue.Body.CustName = CustName;
            inValue.Body.CustTitle = CustTitle;
            inValue.Body.Address = Address;
            NorthWindApplication.ServiceReference1.EditResponse retVal = ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).Edit(inValue);
            return retVal.Body.EditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.EditResponse> NorthWindApplication.ServiceReference1.WebService1Soap.EditAsync(NorthWindApplication.ServiceReference1.EditRequest request) {
            return base.Channel.EditAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.EditResponse> EditAsync(string ID, string CompName, string CustName, string CustTitle, string Address) {
            NorthWindApplication.ServiceReference1.EditRequest inValue = new NorthWindApplication.ServiceReference1.EditRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.EditRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.CompName = CompName;
            inValue.Body.CustName = CustName;
            inValue.Body.CustTitle = CustTitle;
            inValue.Body.Address = Address;
            return ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).EditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWindApplication.ServiceReference1.DeleteResponse NorthWindApplication.ServiceReference1.WebService1Soap.Delete(NorthWindApplication.ServiceReference1.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string ID) {
            NorthWindApplication.ServiceReference1.DeleteRequest inValue = new NorthWindApplication.ServiceReference1.DeleteRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.DeleteRequestBody();
            inValue.Body.ID = ID;
            NorthWindApplication.ServiceReference1.DeleteResponse retVal = ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.DeleteResponse> NorthWindApplication.ServiceReference1.WebService1Soap.DeleteAsync(NorthWindApplication.ServiceReference1.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.DeleteResponse> DeleteAsync(string ID) {
            NorthWindApplication.ServiceReference1.DeleteRequest inValue = new NorthWindApplication.ServiceReference1.DeleteRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.DeleteRequestBody();
            inValue.Body.ID = ID;
            return ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWindApplication.ServiceReference1.OrdersDataResponse NorthWindApplication.ServiceReference1.WebService1Soap.OrdersData(NorthWindApplication.ServiceReference1.OrdersDataRequest request) {
            return base.Channel.OrdersData(request);
        }
        
        public NorthWindApplication.ServiceReference1.OrderDetails[] OrdersData(NorthWindApplication.ServiceReference1.Customer Cust) {
            NorthWindApplication.ServiceReference1.OrdersDataRequest inValue = new NorthWindApplication.ServiceReference1.OrdersDataRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.OrdersDataRequestBody();
            inValue.Body.Cust = Cust;
            NorthWindApplication.ServiceReference1.OrdersDataResponse retVal = ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).OrdersData(inValue);
            return retVal.Body.OrdersDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.OrdersDataResponse> NorthWindApplication.ServiceReference1.WebService1Soap.OrdersDataAsync(NorthWindApplication.ServiceReference1.OrdersDataRequest request) {
            return base.Channel.OrdersDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.OrdersDataResponse> OrdersDataAsync(NorthWindApplication.ServiceReference1.Customer Cust) {
            NorthWindApplication.ServiceReference1.OrdersDataRequest inValue = new NorthWindApplication.ServiceReference1.OrdersDataRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.OrdersDataRequestBody();
            inValue.Body.Cust = Cust;
            return ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).OrdersDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWindApplication.ServiceReference1.PlaceOrderResponse NorthWindApplication.ServiceReference1.WebService1Soap.PlaceOrder(NorthWindApplication.ServiceReference1.PlaceOrderRequest request) {
            return base.Channel.PlaceOrder(request);
        }
        
        public bool PlaceOrder(string CustomerID, int EmployeeID, int ProductID, int Quantity, decimal UnitPrice) {
            NorthWindApplication.ServiceReference1.PlaceOrderRequest inValue = new NorthWindApplication.ServiceReference1.PlaceOrderRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.PlaceOrderRequestBody();
            inValue.Body.CustomerID = CustomerID;
            inValue.Body.EmployeeID = EmployeeID;
            inValue.Body.ProductID = ProductID;
            inValue.Body.Quantity = Quantity;
            inValue.Body.UnitPrice = UnitPrice;
            NorthWindApplication.ServiceReference1.PlaceOrderResponse retVal = ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).PlaceOrder(inValue);
            return retVal.Body.PlaceOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.PlaceOrderResponse> NorthWindApplication.ServiceReference1.WebService1Soap.PlaceOrderAsync(NorthWindApplication.ServiceReference1.PlaceOrderRequest request) {
            return base.Channel.PlaceOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.PlaceOrderResponse> PlaceOrderAsync(string CustomerID, int EmployeeID, int ProductID, int Quantity, decimal UnitPrice) {
            NorthWindApplication.ServiceReference1.PlaceOrderRequest inValue = new NorthWindApplication.ServiceReference1.PlaceOrderRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.PlaceOrderRequestBody();
            inValue.Body.CustomerID = CustomerID;
            inValue.Body.EmployeeID = EmployeeID;
            inValue.Body.ProductID = ProductID;
            inValue.Body.Quantity = Quantity;
            inValue.Body.UnitPrice = UnitPrice;
            return ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).PlaceOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWindApplication.ServiceReference1.AddProductsResponse NorthWindApplication.ServiceReference1.WebService1Soap.AddProducts(NorthWindApplication.ServiceReference1.AddProductsRequest request) {
            return base.Channel.AddProducts(request);
        }
        
        public NorthWindApplication.ServiceReference1.Products[] AddProducts(int ProdID) {
            NorthWindApplication.ServiceReference1.AddProductsRequest inValue = new NorthWindApplication.ServiceReference1.AddProductsRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.AddProductsRequestBody();
            inValue.Body.ProdID = ProdID;
            NorthWindApplication.ServiceReference1.AddProductsResponse retVal = ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).AddProducts(inValue);
            return retVal.Body.AddProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.AddProductsResponse> NorthWindApplication.ServiceReference1.WebService1Soap.AddProductsAsync(NorthWindApplication.ServiceReference1.AddProductsRequest request) {
            return base.Channel.AddProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.AddProductsResponse> AddProductsAsync(int ProdID) {
            NorthWindApplication.ServiceReference1.AddProductsRequest inValue = new NorthWindApplication.ServiceReference1.AddProductsRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.AddProductsRequestBody();
            inValue.Body.ProdID = ProdID;
            return ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).AddProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NorthWindApplication.ServiceReference1.AddEmployeesResponse NorthWindApplication.ServiceReference1.WebService1Soap.AddEmployees(NorthWindApplication.ServiceReference1.AddEmployeesRequest request) {
            return base.Channel.AddEmployees(request);
        }
        
        public NorthWindApplication.ServiceReference1.Employees[] AddEmployees(int EmpID) {
            NorthWindApplication.ServiceReference1.AddEmployeesRequest inValue = new NorthWindApplication.ServiceReference1.AddEmployeesRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.AddEmployeesRequestBody();
            inValue.Body.EmpID = EmpID;
            NorthWindApplication.ServiceReference1.AddEmployeesResponse retVal = ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).AddEmployees(inValue);
            return retVal.Body.AddEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.AddEmployeesResponse> NorthWindApplication.ServiceReference1.WebService1Soap.AddEmployeesAsync(NorthWindApplication.ServiceReference1.AddEmployeesRequest request) {
            return base.Channel.AddEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NorthWindApplication.ServiceReference1.AddEmployeesResponse> AddEmployeesAsync(int EmpID) {
            NorthWindApplication.ServiceReference1.AddEmployeesRequest inValue = new NorthWindApplication.ServiceReference1.AddEmployeesRequest();
            inValue.Body = new NorthWindApplication.ServiceReference1.AddEmployeesRequestBody();
            inValue.Body.EmpID = EmpID;
            return ((NorthWindApplication.ServiceReference1.WebService1Soap)(this)).AddEmployeesAsync(inValue);
        }
    }
}
